### ISSUE TITLE
Suggestion - Add ability to switch off inline css

### ISSUE THREAD

**Issue by jscar** [magento-hackathon/HoneySpam#11]
Could do with the ability to switch off inline css for those that want display:none in an external css file.

**Comment by Schrank** [comment]
The display:none is written by JS because we think some bots might speak css, some bots speak js, but we hope no bot speak both (which is a wrong assumption :))

Therefore: We don't have any inline css - what do expect?

**Comment by kortwotze** [comment]
You are talking about the hidden input field, right? Are you experiencing attacks from bots that speak javascript? If your case is an edge-case (considering this module is mainly intended to defend low-level spam registrations), please explain your edge-case and we can think of a solution.
If you only want it, because you want all your CSS things in one place, I would rather not build that kind of switch, because as @Schrank pointed out, bots can read CSS and I personally think more bots read CSS than JS.

So: Please give a little more detail :)

**Comment by jscar** [comment]
I don't know what the bots are speaking. I wanted it so that all css was in one place. I must admit that I have removed the css hiding from the js file but I am still experiencing the same levels of spam so I will put it back in the js and remove it from my external css to see if it improves :)

Thanks for responding and I beter understand the logic for the way it has been implemented now.

**Comment by kortwotze** [comment]
No worries. What actually should happen is that the whole form element should be injected into the form, right after it is delivered to the browser, so that any bot might not be able to pick it up, yet it gets verified in the shop.
I shall think about that.

**Comment by jscar** [comment]
Just a quick update/observation - since I switched to allowing js to write out the inline css we haven't had any spam at all. Coincidence? Maybe, but I don't think so :)

Thanks

**Comment by michaelscheel** [comment]
Sehr geehrte Damen und Herren,

ich befinden mich bis einschließlich 08.03.2017 nicht im Büro. In dringenden Fälle wenden Sie sich bitte an meinen Kollegen Tobias Völker voelker@virtualways.de.

Mit freundlichen Grüßen 

Michael Scheel

**Comment by sprankhub** [comment]
Since @jscar experienced that the JS / inline CSS part is important, I think we can close this issue.
