### ISSUE TITLE
Need to add Block to Permissions Blocks

### ISSUE THREAD

**Issue by circlesix** [magento-hackathon/HoneySpam#13]
I was getting a 404 when trying to get into the admin section of the module until I added the 'hackathon_honeyspam/honeypot' to the list of allowed blocks (system-> permissions-> blocks).  Once that was in place, i cleared the cache and the sessions and i was able to get into the admin page. Might be nice to toss that info into the setup instructions. 

Thanks for the great module!

**Comment by Schrank** [comment]
I think you misinterpret the Problem.

A 404 in the admin is most of the time a missing ACL. Magento is loading ACL right at the login. So when you install a new module and still have a running authorized session, you get a 404 on the page which checks the ACL, because the now new ACL is not in your session yet.

Logout/Login solves this problem.


Adding a frontend block to the permissions allows the usage in CMS/Mails and other content which allows `{{block type="hackathon_honeyspam/honeypot"}}` syntax. This should not change anything in the backend.
