### ISSUE TITLE
When page has more than one form, honeypot is added only to one

### ISSUE THREAD

**Issue by frain45** [magento-hackathon/HoneySpam#16]
I have installed the extension successfully on a Magento 1.9 site. Pages of this site have, on average, 2 forms for newsletter subscription (left column + footer). 

But the hidden field is added only to one of them. 

At the following URL you can see 3 newsletter subscription forms (left column + body + footer), still the hidden field is added only to the first form created:
http://www.sanditlibri.it/newsletter

Is this a known problem? Any way to work around it?

Best,

Alessandro

**Comment by Schrank** [comment]
@frain45 I would guess, that you implement a second block for the newsletter with its own name and therefore the default is not used. 

You need to add your own block in `local.xml` like:
https://github.com/magento-hackathon/HoneySpam/blob/master/app/design/frontend/base/default/layout/honeyspam.xml#L36-L40

If this doesn't work, please tell me :-)

**Comment by frain45** [comment]
Thanks for the prompt reply!

"I would guess, that you implement a second block for the newsletter with its own name and therefore the default is not used."

The site uses a custom skin with its own newsletter subscription block, but I put the PHP call in it and the first instance of the block on the page does have the hidden "url=" field. The second (and subsequent) instances of the same block, do not have the field.

For example, on page "www.sanditlibri.it/newsletter" there are 3 newsletter blocks. All use the following template:
- path: frontend/[custom package]/[custom skin]/template/newsletter/subscribe.phtml
- name: Mage_Newsletter_Block_Subscribe

The instance of the block in the left column calls frontend/base/default/template/hackathon/honeyspam/honeypot.phtml and has the hidden field. The instances in body and footer, despite using the same template, do not call the honeypot PHTML.

Similar behaviour on the home page www.sanditlibri.it: 2 instances of the same block, left column has honeypot, footer does not.

Is it possible that the honeypot function can be called only once per page?

**Comment by Schrank** [comment]
> Is it possible that the honeypot function can be called only once per page?

Yes possible, but unlikely. Normally in Magento you can call a block as often as you want and if the block doesn't have any logic inside which breaks it, there should be no problem.

I think the problem is, that we create a honeyspam block inside `left.newsletter` and your other newsletter blocks has other names, so copy the XML from https://github.com/magento-hackathon/HoneySpam/blob/master/app/design/frontend/base/default/layout/honeyspam.xml#L36-L40

put it in your local.xml and change the block name.

**Comment by frain45** [comment]
Good catch, I made one step forward.   :-)

I opened the theme's local.xml, located the footer section (<reference name="footer">). Inside it, the newsletter block is referenced (<block type="newsletter/subscribe" name="newsletter" as="newsletter" template="newsletter/subscribe.phtml"/>).

The name is just "newsletter", so I added your code immediately after, editing the reference name:

```
<reference name="newsletter">
   <block type="core/text_list" name="newsletter.form.fields.before" as="form_fields_before" translate="label">
        <block type="hackathon_honeyspam/honeypot" name="honeyspam.honeypot" template="hackathon/honeyspam/honeypot.phtml"/>
    </block>
</reference>
```

Now, the honeypot is included also in the footer form's HTML, and this is the step forward. But the added field is visible! In the "default" block position, left column, the field remains hidden.

I know little about Javascript. Can you help me understand why the module's js does not hide the honeypot in the footer position?

**Comment by Schrank** [comment]
`$('url').hide();` This means: Find "the"  field with the ID `url` and hide it.

Due to the fact, that you have now two fields with the same ID you need:
1. change the name of the field to have each id only once.
2. add a class to catch it easily, like url_field `<input type="..." ... class="url_field"/>`
3. Add some JS (no need to touch the extensions core file) `$$('.url_field').invoke('hide');`

`$$('.url_field').invoke('hide');` means: Find all HTML elements with the class `url_field` (this is an array), call a method on it `hide`

**Comment by Schrank** [comment]
We don't offer free support for a reason, if we do, there is no way we ever earn any money again :-/

If this explanation doesn't solve your problem, please feel free to send me an email for paid support.

**Comment by frain45** [comment]
> We don't offer free support for a reason, if we do, there is no way we ever earn any money again :-/

I understand your point. I found your module as a freely downloadable open source & did not read anywhere about paid support, so I reported a "bug" but it turns out that the module works correctly.

I will try to solve the js issue, and if I manage to get the module fully working , I will offer you a beer via Paypal. Your name seems German so a beer should be the right drink to offer   :-)

As a suggestion, you might add options for custom positions and forms in the Magento admin and then just sell the module for 10 EUR. Honeypot modules for Magento are few, and none is flexible. This way you get something for support, and if a customer/problem is too hard for such a small amount, you can always refund.

**Comment by Schrank** [comment]
We thought about this a lot and we talked with companies and developers who do this: End of the story: Doesn't work for us. We are an association which codes for fun. We have a couple of modules which are maintained and we give our best to fix bugs. But this module is part of the many modules we coded on a hackathon weekend and we use them, because they work, but no one has time for support.

And even if I would have time (aka prioritize it high enough), no one (as in not enough) would ever pay for all the overhead.

Thanks for your understanding. I don't know where are you from, but maybe you want to join us at one of our hackathons ;-) https://shop.firegento.com/

**Comment by frain45** [comment]
Hello Fabian, I followed your suggestions and the problem seems solved. Reporting to help others.

1) In honeypot.phtml I added class="url_field" and left id="url" unchanged. Multiple uses of the same ID on a page is wrong HTML-wise, but in this case does not seem to break anything, because of point 2 .

2) In honeyspam.js I changed $('url').hide(); with $$('.url_field').invoke('hide');

Now the Js looks for "url_field" and there is no error in re-using a class throughout the page. The honeypot is correctly added & hidden to multiple instances of the protected form.

It will be hard for me to attend a Hackaton as I am located in Milano.   :-)    But I donated 10 EUR as promised on shop.firegento.com. Happy drinking!

**Comment by Schrank** [comment]
Thanks for the donation!

One last comment on this, don't change `honeyspam.js`, but instead add your own js file. So updating is easier in the future (not that I expect them for honeyspam, but this is correct for every module - never change the files :-))

**Comment by frain45** [comment]
Yes I got your mentioning of the good practice of "no need to touch the extensions core file". But I spent a lot of time on the honeypot topic & the extension will hardly need updates in the future (it is very focused), So I took the short way.    :-)

Thanks a lot for all your help!
