### ISSUE TITLE
Fatal error: Class 'Hackathon_HoneySpam_Helper_Data' not found 

### ISSUE THREAD

**Issue by cbrugh44** [magento-hackathon/HoneySpam#17]
Hello,

Thanks for your time, I have installed this and after flushing cache in admin panel going to system configuration I am presented with error:
Fatal error: Class 'Hackathon_HoneySpam_Helper_Data' not found in /var/www/httpdocs/app/Mage.php on line 547

Also, the site has a timed popup email sign up form, the homepage has a signup in footer...
will this also place protection on the pop up sign up?
Magento ver. 1.9.2.2
using magento default newsletter signup

**Comment by Schrank** [comment]
Hi @cbrugh44 and thanks for your report.

Please make sure, that you copied the complete module. It seems `app/code/community/Hackathon/HoneySpam/Helper/Data.php` is missing.

The module adds a honeypot to every block which is defined in `app/design/frontend/base/default/layout/honeyspam.xml`. If you have more blocks or other names, you need to add them into your local.xml.

If you need configuring or adating the module, I can offer you paid support.

I hope this helps
Fabian

**Comment by cbrugh44** [comment]
verified that file is present. flushed all caches/sessions, log in/out still only get the error in admin panel when going to system > config.

**Comment by Schrank** [comment]
The class has the right name, so the config.xml is correctly included. If you don't have some weird stuff going on, like symlinking, mounting directories, special autoloader or anything else, I have no clue.

My recommendation is to check the autoloader what it's doing:
https://github.com/OpenMage/magento-mirror/blob/1.9.2.2/lib/Varien/Autoload.php#L82-L95

It should include the file. And the file contains the class. This error doesn't make sense to me. I'm curious to hear what the problem is! :-)

**Comment by cbrugh44** [comment]
had to disable compiler.

**Comment by cbrugh44** [comment]
though I have not been able to successfully see the input field url on frontend, after adding the php call to the custom template www.kwprinters.com

**Comment by Schrank** [comment]
Have a look into https://github.com/magento-hackathon/HoneySpam/issues/16

**Comment by Schrank** [comment]
Thank you very much! https://github.com/magento-hackathon/HoneySpam/commit/db762fdbfbdb9a01331ce1a468ec2ddbcc549542
