### ISSUE TITLE
How do i add this to a custom contact form?

### ISSUE THREAD

**Issue by dhpowrhost** [magento-hackathon/HoneySpam#26]
using a custom template on x-sol.dk using a pop-out contact form. Kontaktformular. How can i put honeyspam in that form? I have added  <?php echo $this->getChildHtml('form_fields_before') ?>
but it does not add the extra form field..

**Comment by sprankhub** [comment]
Add something like [this](https://github.com/magento-hackathon/HoneySpam/blob/9bee9112e37666e196a25193afd0cd04a798e41e/app/design/frontend/base/default/layout/honeyspam.xml#L42) to your layout XML, so that the HoneySpam template is loaded in your `form_fields_before` section. Then, you may have to implement something like [this](https://github.com/magento-hackathon/HoneySpam/blob/9bee9112e37666e196a25193afd0cd04a798e41e/app/code/community/Hackathon/HoneySpam/Model/Observer.php#L60) if your contact form does not use the default `contacts/index/post` route.
