### ISSUE TITLE
HoneySpam on checkout page

### ISSUE THREAD

**Issue by davidelpt** [magento-hackathon/HoneySpam#35]
Hi guys, I'd want to add HoneySpan on checkout page. Could you help me? Thank you.

**Comment by sprankhub** [comment]
You really have issues that bots are creating orders on your page? Never encountered or heard of that issue...

Not sure if it is a good idea to implement this in the module itself since we could break the checkout, which I prefer not to do. Anyway, you could build an extension on top of this extension.

**Comment by erfanimani** [comment]
Yep, same issue here. It's definitely the checkout page, because this time the customer accounts contain address information.

**Comment by erfanimani** [comment]
@davidelpt for now I've gone with this module: https://amasty.com/email-blacklist.html and blacklisted .ru and .cn emails.

**Comment by sprankhub** [comment]
@erfanimani, my question is still if those bots create orders. You just say that it happens on the checkout page. By default, the account is only created during the checkout AFTER you submitted the order. Hence, you should have a fake order as well. If not, maybe there is a custom signup form on your page. Difficult to tell in more detail without knowing the shop...

**Comment by Schrank** [comment]
For the moment I would close the issue - if anything else is to say or thinking about the feature again, feel free to continue conversation here :-)
