### ISSUE TITLE
_checkTimestamp fails during signup due to empty res of getAccountCreateTime

### ISSUE THREAD

**Issue by sebastianrothbucher** [magento-hackathon/HoneySpam#43]
Legit signups are detected as spam b/c getAccountCreateTime (when not yet logged in) returns an empty result. (Magento 1.9.3 CE). I did deactivate the timestamp for the time being - but still: did anyone also encounter the problem and poss. have a solution? Thanks a lot!

**Comment by sprankhub** [comment]
I cannot reproduce this when the account is created on the usual `customer/account/create` page. In this case, the `account_create_time` is correctly set and checked. Where do you create the account? It is probably on another page, right?

**Comment by sebastianrothbucher** [comment]
in fact, it is exactly the page you mentioned; and ```$session->getAccountCreateTime(false)``` returns precisely nothing.

**Comment by sprankhub** [comment]
Never heard of this issue. But the module is tiny, so debugging should not be too hard. You obviously already debugged `Hackathon_HoneySpam_Model_Observer::_checkTimestamp`, because you say that `$session->getAccountCreateTime(false)` returns nothing. Then you can easily also debug `Hackathon_HoneySpam_Model_Observer::controllerActionPredispatchCustomerAccountCreate`. This method should be called each time the page `customer/account/create` is opened. In it, the `account_create_time` is set. Please check that and give us feedback.

**Comment by sprankhub** [comment]
Closing this due to lack of feedback.
